In [9]:
import pandas as pd
df = pd.read_parquet('datas/students.parquet')

In [6]:
import pandas as pd
df = pd.read_parquet('datas/students.parquet')
newdf = df.loc[(df['Algorithm Marks']>80) & (df['Python Marks']>85),['Algorithm Marks','Python Marks']]
print(newdf)
print(newdf.dtypes)

    Algorithm Marks  Python Marks
0              85.0          88.0
9              89.0          88.0
11             85.0          87.0
16             90.0          93.0
19             86.0          89.0
Algorithm Marks    float64
Python Marks       float64
dtype: object

In [7]:
import pandas as pd 
df = pd.read_json('datas/customers.json')
df = df[df['name'].str.len()>4]
df

   id     name
0   1    Alice
2   3  Charlie
3   4    Diana
4   5    Ethan
5   6    Fiona
6   7   George
7   8   Hannah

In [8]:
name = 'shakib'
name.startswith('S')

False

In [13]:
df['Algorithm Marks'].clip(lower=89, upper=90)

0     89.0
1     90.0
2     89.0
3     89.0
4      NaN
5     89.0
6     89.0
7     89.0
8     89.0
9     89.0
10     NaN
11    89.0
12    89.0
13     NaN
14    89.0
15    90.0
16    90.0
17    89.0
18     NaN
19    89.0
Name: Algorithm Marks, dtype: float64

In [33]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana'],
    'Education': ['High School', 'Bachelor', 'Master', 'PhD']
}

df = pd.DataFrame(data)
mapping = {'High School': 1, 'Bachelor': 2, 'Master': 3, 'PhD': 4}
df['Education'] = df['Education'].map(mapping )
# df['Education'] = df['Education'].apply(lambda x: mapping[x] )

df

      Name  Education
0    Alice          1
1      Bob          2
2  Charlie          3
3    Diana          4

In [43]:
import numpy as np

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Evan'],
    'Age': [25, np.nan, 30, 28, np.nan],
    'City': ['New York', 'London', np.nan, 'Paris', 'Tokyo'],
    'Education': ['Bachelor', np.nan, 'Master', 'PhD', 'High School']
}
df = pd.DataFrame(data)
print(df['City'].isnull().sum())
for c in ['Name','Age','City','Education']:
    df[c]=df[c].fillna("missing")
print(df['City'].isnull().sum())

1
0