In [115]:
import numpy as np
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [116]:
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36"
}
res = requests.get('https://en.wikipedia.org/wiki/List_of_companies_of_Bangladesh',headers=headers).text

In [117]:
soup = BeautifulSoup(res)
table = soup.find('table')
trs = table.find_all('tr')

In [118]:
company = []
industry = []
sector = []
headquarter = []
founded = []
for tr in trs[2:]:
    tds = tr.find_all('td')
    company.append(tds[0].text.strip())
    industry.append(tds[1].text.strip())
    sector.append(tds[2].text.strip())
    headquarter.append(tds[3].text.strip())
    founded.append(tds[4].text.strip())

dct = dict({'company':company, 'industry':industry,'sector':sector,'headquarter':headquarter,'founded':founded})

df = pd.DataFrame(dct)
df.head()

,company,industry,sector,headquarter,founded
0,A K Khan & Company,Conglomerates,-,Chittagong,1945
1,Aarong,Consumer goods,Personal & household goods,Dhaka,1978
2,Abul Khair Group,Conglomerates,-,Chattogram,1953
3,Adamjee Jute Mills,Consumer goods,Clothing & accessories,Narayanganj,1951
4,Advanced Chemical Industries (ACI),Conglomerates,-,Dhaka,1968

In [119]:
# df.loc[df['sector']=='-', 'sector']=np.nan
df['sector']=df['sector'].replace('-',np.nan)
display(df.head(50))
display(df.info())

,company,industry,sector,headquarter,founded
0,A K Khan & Company,Conglomerates,NaN,Chittagong,1945
1,Aarong,Consumer goods,Personal & household goods,Dhaka,1978
2,Abul Khair Group,Conglomerates,NaN,Chattogram,1953
3,Adamjee Jute Mills,Consumer goods,Clothing & accessories,Narayanganj,1951
4,Advanced Chemical Industries (ACI),Conglomerates,NaN,Dhaka,1968
5,Agamee Prakashani,Consumer services,Publishing,Dhaka,1986
6,Agrani Bank,Financials,Banks,Dhaka,1972
7,Airtel Bangladesh,Telecommunications,Mobile telecommunications,Dhaka,2007
8,Akij,Conglomerates,NaN,Dhaka,1940
9,Alim Industries Limited,Industrials,NaN,Sylhet,1990
10,Amar Desh,Consumer services,Publishing,Dhaka,2004
11,Adamjee Jute Mills,Consumer goods,Clothing & accessories,Narayanganj,1951
12,Asian TV,Consumer services,Broadcasting & entertainment,Dhaka,2013
13,ATN Bangla,Consumer services,Broadcasting & entertainment,Dhaka,1997
14,ATN News,Consumer services,Broadcasting & entertainment,Dhaka,2010
15,Bangladesh Bank,Financials,Banks,Dhaka,1971
16,Bangladesh Betar,Consumer services,Broadcasting & entertainment,Dhaka,1939
17,Bangladesh Machine Tools Factory,Industrials,Defense,Gazipur City,1979
18,Bangladesh Petroleum Corporation,Oil & gas,Exploration & production,Dhaka,1976
19,Bangladesh Pratidin,Consumer services,Publishing,Dhaka,2010
20,Bangladesh Railway,Industrials,Railroads,Dhaka,1862
21,Bangladesh Shipping Corporation,Industrials,Marine transportation,Chittagong,1972
22,Bangladesh Telecommunications Company Limited,Telecommunications,Mobile telecommunications,Dhaka,1971
23,Bangladesh Television,Consumer services,Broadcasting & entertainment,Dhaka,1964
24,Banglalink,Telecommunications,Mobile telecommunications,Dhaka,1996
25,Banglalion,Telecommunications,Mobile telecommunications,Dhaka,2008
26,Banglavision,Consumer services,Broadcasting & entertainment,Dhaka,2006
27,Bashundhara Group,Conglomerates,"Real estate, media, manufacturing, retail, and...",Dhaka,1987
28,Bengal Group,Conglomerates,NaN,Dhaka,1969
29,Best Air,Consumer services,Airlines,Dhaka,2007
30,Beximco Pharma,Health care,Pharmaceuticals,Gazipur City,1980
31,Beximco,Conglomerates,NaN,Dhaka,1972
32,Bhorer Kagoj,Consumer services,Publishing,Dhaka,1992
33,Bikroy.com,Technology,Software,Dhaka,2012
34,Biman Bangladesh Airlines,Consumer services,Airlines,Dhaka,1972
35,Bismillah Airlines,Consumer services,Airlines,Dhaka,1998
36,Bismillah Group,Consumer goods,Clothing & accessories,Dhaka,1988
37,BRAC Bank Limited,Financials,Banks,Dhaka,2001
38,BSRM,Basic materials,Iron & steel,Chittagong,1952
39,BTCL,Telecommunications,Fixed line telecommunications,Dhaka,1971
40,Building Technology & Ideas,Financials,Real estate holding & development,Dhaka,1984
41,Channel 9,Consumer services,Broadcasting & entertainment,Dhaka,2011
42,Channel 24,Consumer services,Broadcasting & entertainment,Dhaka,2012
43,Channel i,Consumer services,Broadcasting & entertainment,Dhaka,1999
44,City Group,Conglomerates,NaN,Dhaka,1972
45,Citycell,Telecommunications,Mobile telecommunications,Dhaka,1989
46,Concord Group,Conglomerates,Construction and real estate,Dhaka,1973
47,Confidence Group,Conglomerates,Engineering and power generation,Dhaka,1991
48,Cooper's,Consumer goods,Food & beverage,Dhaka,1984
49,Credit Rating Information and Services Limited...,Financials,Consumer finance,Dhaka,1992

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 174 entries, 0 to 173
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   company      174 non-null    object
 1   industry     174 non-null    object
 2   sector       142 non-null    object
 3   headquarter  174 non-null    object
 4   founded      174 non-null    object
dtypes: object(5)
memory usage: 6.9+ KB

None

In [121]:
newdf = df.dropna()
display(newdf.info())
display(newdf.head(50))

<class 'pandas.core.frame.DataFrame'>
Index: 142 entries, 1 to 173
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   company      142 non-null    object
 1   industry     142 non-null    object
 2   sector       142 non-null    object
 3   headquarter  142 non-null    object
 4   founded      142 non-null    object
dtypes: object(5)
memory usage: 6.7+ KB

None

,company,industry,sector,headquarter,founded
1,Aarong,Consumer goods,Personal & household goods,Dhaka,1978
3,Adamjee Jute Mills,Consumer goods,Clothing & accessories,Narayanganj,1951
5,Agamee Prakashani,Consumer services,Publishing,Dhaka,1986
6,Agrani Bank,Financials,Banks,Dhaka,1972
7,Airtel Bangladesh,Telecommunications,Mobile telecommunications,Dhaka,2007
10,Amar Desh,Consumer services,Publishing,Dhaka,2004
11,Adamjee Jute Mills,Consumer goods,Clothing & accessories,Narayanganj,1951
12,Asian TV,Consumer services,Broadcasting & entertainment,Dhaka,2013
13,ATN Bangla,Consumer services,Broadcasting & entertainment,Dhaka,1997
14,ATN News,Consumer services,Broadcasting & entertainment,Dhaka,2010
15,Bangladesh Bank,Financials,Banks,Dhaka,1971
16,Bangladesh Betar,Consumer services,Broadcasting & entertainment,Dhaka,1939
17,Bangladesh Machine Tools Factory,Industrials,Defense,Gazipur City,1979
18,Bangladesh Petroleum Corporation,Oil & gas,Exploration & production,Dhaka,1976
19,Bangladesh Pratidin,Consumer services,Publishing,Dhaka,2010
20,Bangladesh Railway,Industrials,Railroads,Dhaka,1862
21,Bangladesh Shipping Corporation,Industrials,Marine transportation,Chittagong,1972
22,Bangladesh Telecommunications Company Limited,Telecommunications,Mobile telecommunications,Dhaka,1971
23,Bangladesh Television,Consumer services,Broadcasting & entertainment,Dhaka,1964
24,Banglalink,Telecommunications,Mobile telecommunications,Dhaka,1996
25,Banglalion,Telecommunications,Mobile telecommunications,Dhaka,2008
26,Banglavision,Consumer services,Broadcasting & entertainment,Dhaka,2006
27,Bashundhara Group,Conglomerates,"Real estate, media, manufacturing, retail, and...",Dhaka,1987
29,Best Air,Consumer services,Airlines,Dhaka,2007
30,Beximco Pharma,Health care,Pharmaceuticals,Gazipur City,1980
32,Bhorer Kagoj,Consumer services,Publishing,Dhaka,1992
33,Bikroy.com,Technology,Software,Dhaka,2012
34,Biman Bangladesh Airlines,Consumer services,Airlines,Dhaka,1972
35,Bismillah Airlines,Consumer services,Airlines,Dhaka,1998
36,Bismillah Group,Consumer goods,Clothing & accessories,Dhaka,1988
37,BRAC Bank Limited,Financials,Banks,Dhaka,2001
38,BSRM,Basic materials,Iron & steel,Chittagong,1952
39,BTCL,Telecommunications,Fixed line telecommunications,Dhaka,1971
40,Building Technology & Ideas,Financials,Real estate holding & development,Dhaka,1984
41,Channel 9,Consumer services,Broadcasting & entertainment,Dhaka,2011
42,Channel 24,Consumer services,Broadcasting & entertainment,Dhaka,2012
43,Channel i,Consumer services,Broadcasting & entertainment,Dhaka,1999
45,Citycell,Telecommunications,Mobile telecommunications,Dhaka,1989
46,Concord Group,Conglomerates,Construction and real estate,Dhaka,1973
47,Confidence Group,Conglomerates,Engineering and power generation,Dhaka,1991
48,Cooper's,Consumer goods,Food & beverage,Dhaka,1984
49,Credit Rating Information and Services Limited...,Financials,Consumer finance,Dhaka,1992
50,Daily Inqilab,Consumer services,Publishing,Dhaka,1986
51,DBC News,Consumer services,Broadcasting & entertainment,Dhaka,2016
52,DBL Group,Conglomerates,,Dhaka,1991
53,Deepto TV,Consumer services,Broadcasting & entertainment,Dhaka,2015
54,Delta Brac Housing Finance Corporation,Financials,Consumer finance,Dhaka,1996
55,Desh TV,Consumer services,Broadcasting & entertainment,Dhaka,2009
56,Dhaka Bank Limited,Financials,Banks,Dhaka,1995
57,Dragon Group,Consumer goods,Clothing & accessories,Dhaka,1980