In [23]:
import pandas as pd
df = pd.read_json('datas/students_data.json')
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka
20,PH1021,Rumana Sultana,91.0,89.0,90.0,Completed,2025-10-12,Mr. Karim,Khulna
21,PH1022,Shafiqul Islam,84.0,86.0,NaN,In Progress,2025-10-15,Ms. Salma,Dhaka
22,PH1023,Tahsin Ahmed,77.0,79.0,82.0,Completed,2025-10-20,Mr. David,Rajshahi
23,PH1024,Mehnaz Chowdhury,NaN,NaN,NaN,Not Started,2025-10-25,Ms. Salma,Sylhet
24,PH1025,Tareq Aziz,93.0,95.0,96.0,Completed,2025-10-30,Mr. Karim,Dhaka

In [24]:
def generate_marks(marks):
    if(pd.isna(marks)):
        return 0
    result = 0
    a = int(marks%10)
    if(a>5):
        x = int(marks/10)
        result=(x*10)+10
    else:
        y = int(marks/10)
        result = y*10
    return result
    
df['New DS Marks']=df['Data Structure Marks'].apply(generate_marks)
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,New DS Marks
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,80
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,90
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,90
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,80
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,0
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,70
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,80
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,80
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,70
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,90
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,0
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,80
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,70
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,0
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,90
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,90
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,90
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,90
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram,0
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,90
20,PH1021,Rumana Sultana,91.0,89.0,90.0,Completed,2025-10-12,Mr. Karim,Khulna,90
21,PH1022,Shafiqul Islam,84.0,86.0,NaN,In Progress,2025-10-15,Ms. Salma,Dhaka,80
22,PH1023,Tahsin Ahmed,77.0,79.0,82.0,Completed,2025-10-20,Mr. David,Rajshahi,80
23,PH1024,Mehnaz Chowdhury,NaN,NaN,NaN,Not Started,2025-10-25,Ms. Salma,Sylhet,0
24,PH1025,Tareq Aziz,93.0,95.0,96.0,Completed,2025-10-30,Mr. Karim,Dhaka,90

In [25]:
def generate_marks(marks):
    if(pd.isna(marks)):
        return 0
    result = 0
    a = int(marks%10)
    if(a>5):
        x = int(marks/10)
        result=(x*10)+10
    else:
        y = int(marks/10)
        result = y*10
    return result
    
df.insert(5,'New Python Marks',df['Python Marks'].apply(generate_marks))
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,New Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,New DS Marks
0,PH1001,Alif Rahman,85.0,85.0,88.0,90,Completed,2024-01-15,Mr. Karim,Dhaka,80
1,PH1002,Fatima Akhter,92.0,92.0,NaN,0,In Progress,2024-01-20,Ms. Salma,Chattogram,90
2,PH1003,Imran Hossain,88.0,88.0,85.0,80,Completed,2024-02-10,Mr. Karim,Dhaka,90
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,80,Completed,2024-02-12,Ms. Salma,Sylhet,80
4,PH1005,Kamal Uddin,NaN,NaN,95.0,90,In Progress,2024-03-05,Mr. Karim,Chattogram,0
5,PH1006,Laila Begum,75.0,75.0,78.0,80,Completed,2024-03-08,Ms. Salma,Rajshahi,70
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,0,In Progress,2024-04-01,Mr. Karim,Dhaka,80
7,PH1008,Nadia Islam,81.0,81.0,85.0,80,Completed,2024-04-22,Ms. Salma,Chattogram,80
8,PH1009,Omar Faruq,72.0,72.0,76.0,80,Completed,2024-05-16,Mr. David,Dhaka,70
9,PH1010,Priya Sharma,89.0,89.0,88.0,90,Completed,2024-05-20,Ms. Salma,Sylhet,90
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,90,In Progress,2024-06-11,Mr. Karim,Khulna,0
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,90,Completed,2024-06-14,Ms. Salma,Chattogram,80
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,80,Completed,2024-07-02,Mr. David,Dhaka,70
13,PH1014,Urmi Akter,NaN,NaN,NaN,0,Not Started,2024-07-09,Ms. Salma,Rajshahi,0
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,80,Completed,2024-08-18,Mr. Karim,Dhaka,90
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,0,In Progress,2024-08-21,Ms. Salma,Chattogram,90
16,PH1017,Afsana Mimi,90.0,90.0,93.0,90,Completed,2025-09-01,Mr. Karim,Dhaka,90
17,PH1018,Babul Ahmed,88.0,88.0,85.0,80,Completed,2025-09-05,Ms. Salma,Sylhet,90
18,PH1019,Faria Rahman,NaN,NaN,NaN,0,Not Started,2025-09-15,Mr. David,Chattogram,0
19,PH1020,Nasir Khan,86.0,86.0,89.0,90,Completed,2025-10-02,Ms. Salma,Dhaka,90
20,PH1021,Rumana Sultana,91.0,89.0,90.0,90,Completed,2025-10-12,Mr. Karim,Khulna,90
21,PH1022,Shafiqul Islam,84.0,86.0,NaN,0,In Progress,2025-10-15,Ms. Salma,Dhaka,80
22,PH1023,Tahsin Ahmed,77.0,79.0,82.0,80,Completed,2025-10-20,Mr. David,Rajshahi,80
23,PH1024,Mehnaz Chowdhury,NaN,NaN,NaN,0,Not Started,2025-10-25,Ms. Salma,Sylhet,0
24,PH1025,Tareq Aziz,93.0,95.0,96.0,100,Completed,2025-10-30,Mr. Karim,Dhaka,90

In [26]:
# change the nan value to 0 as change others ot half
df['Algorithm Marks']=df['Algorithm Marks'].apply(lambda x: '-' if pd.isna(x) else int(x/2))
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,New Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,New DS Marks
0,PH1001,Alif Rahman,85.0,42,88.0,90,Completed,2024-01-15,Mr. Karim,Dhaka,80
1,PH1002,Fatima Akhter,92.0,46,NaN,0,In Progress,2024-01-20,Ms. Salma,Chattogram,90
2,PH1003,Imran Hossain,88.0,44,85.0,80,Completed,2024-02-10,Mr. Karim,Dhaka,90
3,PH1004,Jannatul Ferdous,78.0,39,82.0,80,Completed,2024-02-12,Ms. Salma,Sylhet,80
4,PH1005,Kamal Uddin,NaN,-,95.0,90,In Progress,2024-03-05,Mr. Karim,Chattogram,0
5,PH1006,Laila Begum,75.0,37,78.0,80,Completed,2024-03-08,Ms. Salma,Rajshahi,70
6,PH1007,Mahmudul Hasan,80.0,40,NaN,0,In Progress,2024-04-01,Mr. Karim,Dhaka,80
7,PH1008,Nadia Islam,81.0,40,85.0,80,Completed,2024-04-22,Ms. Salma,Chattogram,80
8,PH1009,Omar Faruq,72.0,36,76.0,80,Completed,2024-05-16,Mr. David,Dhaka,70
9,PH1010,Priya Sharma,89.0,44,88.0,90,Completed,2024-05-20,Ms. Salma,Sylhet,90
10,PH1011,Rahim Sheikh,NaN,-,91.0,90,In Progress,2024-06-11,Mr. Karim,Khulna,0
11,PH1012,Sadia Chowdhury,85.0,42,87.0,90,Completed,2024-06-14,Ms. Salma,Chattogram,80
12,PH1013,Tanvir Ahmed,75.0,37,79.0,80,Completed,2024-07-02,Mr. David,Dhaka,70
13,PH1014,Urmi Akter,NaN,-,NaN,0,Not Started,2024-07-09,Ms. Salma,Rajshahi,0
14,PH1015,Wahiduzzaman,86.0,43,84.0,80,Completed,2024-08-18,Mr. Karim,Dhaka,90
15,PH1016,Ziaur Rahman,94.0,47,NaN,0,In Progress,2024-08-21,Ms. Salma,Chattogram,90
16,PH1017,Afsana Mimi,90.0,45,93.0,90,Completed,2025-09-01,Mr. Karim,Dhaka,90
17,PH1018,Babul Ahmed,88.0,44,85.0,80,Completed,2025-09-05,Ms. Salma,Sylhet,90
18,PH1019,Faria Rahman,NaN,-,NaN,0,Not Started,2025-09-15,Mr. David,Chattogram,0
19,PH1020,Nasir Khan,86.0,43,89.0,90,Completed,2025-10-02,Ms. Salma,Dhaka,90
20,PH1021,Rumana Sultana,91.0,44,90.0,90,Completed,2025-10-12,Mr. Karim,Khulna,90
21,PH1022,Shafiqul Islam,84.0,43,NaN,0,In Progress,2025-10-15,Ms. Salma,Dhaka,80
22,PH1023,Tahsin Ahmed,77.0,39,82.0,80,Completed,2025-10-20,Mr. David,Rajshahi,80
23,PH1024,Mehnaz Chowdhury,NaN,-,NaN,0,Not Started,2025-10-25,Ms. Salma,Sylhet,0
24,PH1025,Tareq Aziz,93.0,47,96.0,100,Completed,2025-10-30,Mr. Karim,Dhaka,90