In [1]:
import pandas as pd
data = {
  "name": ["Alice", "Bob", "Charlie", "Diana", "Ethan", "Fiona", "George", "Hannah",],
  "city": ["New York", "Los Angeles", "Chicago", "Houston", "Miami", "Seattle", "Boston New", "Denver"],
  "department": ["HR", "IT", "Finance", "Marketing", "IT", "HR", "Operations", "Finance"],
  "salary": [5500, 7200, 6800, 6100, 7500, 5300, 7000, 6600]
}
df = pd.DataFrame(data)
df

      name         city  department  salary
0    Alice     New York          HR    5500
1      Bob  Los Angeles          IT    7200
2  Charlie      Chicago     Finance    6800
3    Diana      Houston   Marketing    6100
4    Ethan        Miami          IT    7500
5    Fiona      Seattle          HR    5300
6   George   Boston New  Operations    7000
7   Hannah       Denver     Finance    6600

In [2]:
df[['name']]

      name
0    Alice
1      Bob
2  Charlie
3    Diana
4    Ethan
5    Fiona
6   George
7   Hannah

In [3]:
# Letter A exists or not
df.loc[df['city'].str.contains('New')]

     name        city  department  salary
0   Alice    New York          HR    5500
6  George  Boston New  Operations    7000

In [4]:
# starts with New word
df.loc[df['city'].str.contains('^New')]

    name      city department  salary
0  Alice  New York         HR    5500

In [5]:
# Ends with New word
df.loc[df['city'].str.contains('New$')]

     name        city  department  salary
6  George  Boston New  Operations    7000

In [6]:
# stop case sensitivity
df.loc[df['city'].str.contains('e',case=False)]

     name         city  department  salary
0   Alice     New York          HR    5500
1     Bob  Los Angeles          IT    7200
5   Fiona      Seattle          HR    5300
6  George   Boston New  Operations    7000
7  Hannah       Denver     Finance    6600

In [7]:
# create a new column named average marks
import pandas as pd 
df = pd.read_json('datas/students_data.json')
# df['average_marks']=(df['Data Structure Marks']+df['Python Marks']+df['Algorithm Marks'])/3
df['average_marks']=round((df['Data Structure Marks']+df['Python Marks']+df['Algorithm Marks'])/3,2)
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,average_marks
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,86.00
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,NaN
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,87.00
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,79.33
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,NaN
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,76.00
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,NaN
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,82.33
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,73.33
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,88.67
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,NaN
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,85.67
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,76.33
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,NaN
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,85.33
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,NaN
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,91.00
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,87.00
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram,NaN
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,87.00
20,PH1021,Rumana Sultana,91.0,89.0,90.0,Completed,2025-10-12,Mr. Karim,Khulna,90.00
21,PH1022,Shafiqul Islam,84.0,86.0,NaN,In Progress,2025-10-15,Ms. Salma,Dhaka,NaN
22,PH1023,Tahsin Ahmed,77.0,79.0,82.0,Completed,2025-10-20,Mr. David,Rajshahi,79.33
23,PH1024,Mehnaz Chowdhury,NaN,NaN,NaN,Not Started,2025-10-25,Ms. Salma,Sylhet,NaN
24,PH1025,Tareq Aziz,93.0,95.0,96.0,Completed,2025-10-30,Mr. Karim,Dhaka,94.67

In [8]:
# change nan value to 0 in Python Marks column
import numpy as np
df['Python Marks'] = np.where(df['Python Marks'].isna(), 0, df['Python Marks'])
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,average_marks
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,86.00
1,PH1002,Fatima Akhter,92.0,92.0,0.0,In Progress,2024-01-20,Ms. Salma,Chattogram,NaN
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,87.00
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,79.33
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,NaN
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,76.00
6,PH1007,Mahmudul Hasan,80.0,80.0,0.0,In Progress,2024-04-01,Mr. Karim,Dhaka,NaN
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,82.33
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,73.33
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,88.67
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,NaN
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,85.67
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,76.33
13,PH1014,Urmi Akter,NaN,NaN,0.0,Not Started,2024-07-09,Ms. Salma,Rajshahi,NaN
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,85.33
15,PH1016,Ziaur Rahman,94.0,94.0,0.0,In Progress,2024-08-21,Ms. Salma,Chattogram,NaN
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,91.00
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,87.00
18,PH1019,Faria Rahman,NaN,NaN,0.0,Not Started,2025-09-15,Mr. David,Chattogram,NaN
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,87.00
20,PH1021,Rumana Sultana,91.0,89.0,90.0,Completed,2025-10-12,Mr. Karim,Khulna,90.00
21,PH1022,Shafiqul Islam,84.0,86.0,0.0,In Progress,2025-10-15,Ms. Salma,Dhaka,NaN
22,PH1023,Tahsin Ahmed,77.0,79.0,82.0,Completed,2025-10-20,Mr. David,Rajshahi,79.33
23,PH1024,Mehnaz Chowdhury,NaN,NaN,0.0,Not Started,2025-10-25,Ms. Salma,Sylhet,NaN
24,PH1025,Tareq Aziz,93.0,95.0,96.0,Completed,2025-10-30,Mr. Karim,Dhaka,94.67

In [9]:
# check unique 
print(df['Algorithm Marks'].unique())
len(df['Algorithm Marks'].unique())

[85. 92. 88. 78. nan 75. 80. 81. 72. 89. 86. 94. 90. 79. 95.]

15

In [10]:
# check unique exclude NaN
print(df['Algorithm Marks'].nunique())

14

In [11]:
df.isnull()

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,average_marks
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,True
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,True,True,False,False,False,False,False,True
5,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,True
7,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False
10,False,False,True,True,False,False,False,False,False,True
11,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False
13,False,False,True,True,False,False,False,False,False,True
14,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,True
16,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False
18,False,False,True,True,False,False,False,False,False,True
19,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,True
22,False,False,False,False,False,False,False,False,False,False
23,False,False,True,True,False,False,False,False,False,True
24,False,False,False,False,False,False,False,False,False,False

In [12]:
df.notnull()

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,average_marks
0,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,False
2,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True
4,True,True,False,False,True,True,True,True,True,False
5,True,True,True,True,True,True,True,True,True,True
6,True,True,True,True,True,True,True,True,True,False
7,True,True,True,True,True,True,True,True,True,True
8,True,True,True,True,True,True,True,True,True,True
9,True,True,True,True,True,True,True,True,True,True
10,True,True,False,False,True,True,True,True,True,False
11,True,True,True,True,True,True,True,True,True,True
12,True,True,True,True,True,True,True,True,True,True
13,True,True,False,False,True,True,True,True,True,False
14,True,True,True,True,True,True,True,True,True,True
15,True,True,True,True,True,True,True,True,True,False
16,True,True,True,True,True,True,True,True,True,True
17,True,True,True,True,True,True,True,True,True,True
18,True,True,False,False,True,True,True,True,True,False
19,True,True,True,True,True,True,True,True,True,True
20,True,True,True,True,True,True,True,True,True,True
21,True,True,True,True,True,True,True,True,True,False
22,True,True,True,True,True,True,True,True,True,True
23,True,True,False,False,True,True,True,True,True,False
24,True,True,True,True,True,True,True,True,True,True

In [13]:
df.duplicated(subset='Python Marks')

0     False
1     False
2     False
3     False
4     False
5     False
6      True
7      True
8     False
9      True
10    False
11    False
12    False
13     True
14    False
15     True
16    False
17     True
18     True
19    False
20    False
21     True
22     True
23     True
24    False
dtype: bool

In [14]:
df.drop_duplicates("Python Marks")

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,average_marks
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,86.00
1,PH1002,Fatima Akhter,92.0,92.0,0.0,In Progress,2024-01-20,Ms. Salma,Chattogram,NaN
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,87.00
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,79.33
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,NaN
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,76.00
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,73.33
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,NaN
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,85.67
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,76.33
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,85.33
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,91.00
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,87.00
20,PH1021,Rumana Sultana,91.0,89.0,90.0,Completed,2025-10-12,Mr. Karim,Khulna,90.00
24,PH1025,Tareq Aziz,93.0,95.0,96.0,Completed,2025-10-30,Mr. Karim,Dhaka,94.67

In [15]:
df.fillna(0)

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,average_marks
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,86.00
1,PH1002,Fatima Akhter,92.0,92.0,0.0,In Progress,2024-01-20,Ms. Salma,Chattogram,0.00
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,87.00
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,79.33
4,PH1005,Kamal Uddin,0.0,0.0,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,0.00
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,76.00
6,PH1007,Mahmudul Hasan,80.0,80.0,0.0,In Progress,2024-04-01,Mr. Karim,Dhaka,0.00
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,82.33
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,73.33
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,88.67
10,PH1011,Rahim Sheikh,0.0,0.0,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,0.00
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,85.67
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,76.33
13,PH1014,Urmi Akter,0.0,0.0,0.0,Not Started,2024-07-09,Ms. Salma,Rajshahi,0.00
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,85.33
15,PH1016,Ziaur Rahman,94.0,94.0,0.0,In Progress,2024-08-21,Ms. Salma,Chattogram,0.00
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,91.00
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,87.00
18,PH1019,Faria Rahman,0.0,0.0,0.0,Not Started,2025-09-15,Mr. David,Chattogram,0.00
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,87.00
20,PH1021,Rumana Sultana,91.0,89.0,90.0,Completed,2025-10-12,Mr. Karim,Khulna,90.00
21,PH1022,Shafiqul Islam,84.0,86.0,0.0,In Progress,2025-10-15,Ms. Salma,Dhaka,0.00
22,PH1023,Tahsin Ahmed,77.0,79.0,82.0,Completed,2025-10-20,Mr. David,Rajshahi,79.33
23,PH1024,Mehnaz Chowdhury,0.0,0.0,0.0,Not Started,2025-10-25,Ms. Salma,Sylhet,0.00
24,PH1025,Tareq Aziz,93.0,95.0,96.0,Completed,2025-10-30,Mr. Karim,Dhaka,94.67